#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 1

#define LV_TICK_CUSTOM 0
#define LV_USE_LOG 0

#define LV_USE_DRAW_SW_COMPLEX_GRADIENTS 1
#define LV_OBJ_STYLE_CACHE      1
#define LV_USE_LOG	        1
#define LV_LOG_PRINTF	    1
#define LV_USE_ASSERT_MEM_INTEGRITY	1
#define LV_USE_ASSERT_OBJ	1
#define LV_USE_ASSERT_STYLE	1
#define LV_FONT_MONTSERRAT_12	1
#define LV_FONT_MONTSERRAT_14	1
#define LV_FONT_MONTSERRAT_16	1
#define LV_FONT_MONTSERRAT_18	1
#define LV_FONT_MONTSERRAT_20	1
#define LV_FONT_MONTSERRAT_22	1
#define LV_FONT_MONTSERRAT_24	1
#define LV_FONT_MONTSERRAT_26	1
#define LV_FONT_MONTSERRAT_28	1
#define LV_FONT_MONTSERRAT_30	1
#define LV_FONT_MONTSERRAT_32	1
#define LV_FONT_MONTSERRAT_34	1
#define LV_FONT_MONTSERRAT_36	1
#define LV_FONT_MONTSERRAT_38	1
#define LV_FONT_MONTSERRAT_40	1
#define LV_FONT_MONTSERRAT_42	1
#define LV_FONT_MONTSERRAT_44	1
#define LV_FONT_MONTSERRAT_46	1
#define LV_FONT_MONTSERRAT_48	1
#define LV_FONT_MONTSERRAT_28_COMPRESSED	1
#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW	1
#define LV_FONT_SIMSUN_16_CJK	1
#define LV_FONT_UNSCII_8	1

#endif
